name: First Workflow

on:
  push:

jobs: # this is also refer as stages - inside stages we are having multiple stage such as build stage, test stage, deploy stage
  build_stage: #This is also refer as first stage or job
    runs-on: ubuntu-latest  # this is refer as runner means in this stage will run - we can use windows-latest, macos-latest, ubuntu-latest

    steps:
      - name: Print message
        run: echo "build stage is running"
      - name: Print current directory
        run: pwd
  test_stage: ##This is also refer as second stage or job
    needs: build_stage # this is refer as dependency means this stage will run after build stage
    runs-on: ubuntu-latest # this is refer as runner means in this stage will run - we can use windows-latest, macos-latest, ubuntu-latest

    steps:
      - name: Print message
        run: echo "test stage is running"