name: First Workflow

on:
  push:

jobs: # this is also refer as stages - inside stages we are having multiple stage such as build stage, test stage, deploy stage
  build_stage: #This is also refer as first stage or job
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "build stage is running"
  test_stage: ##This is also refer as second stage or job
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "test stage is running"