name: Simple Node.js CI
#WORK F LOW LEVEL ENVIRONMENT VARIABLES
env:
    APP_NAME: Simple-Node.js-CI
on:
    push:
        paths:
            - 'simple-nodejs-ci/**'
            - '.github/workflows/simple-nodejs-ci.yml' # path based trigger for workflow file changes
jobs:
    ci_pipeline_stage:
        runs-on: ubuntu-latest
        steps:
            - name: checking my workflow level environment variable
              run: echo $APP_NAME

            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 18

            - name: Install dependencies
              run: npm install && pwd
              working-directory: simple-nodejs-ci/
            
            - name: Run tests
              run: npm test
              working-directory: simple-nodejs-ci/

            - name: start application
              run: npm start
              working-directory: simple-nodejs-ci/
